### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by aproposnix** [Reditr-Software/reditr#14]
Hi Reditr team, 

First, I really want to say I love Reditr.  I've been using it for years and can't imagine what I would do without it (well, I guess I wouldn't be on reddit much :) 

Anyway, I'm just curious about the status of the project. The FOSS version was announced pretty long ago but there have been no releases. Is the project still active? 

thanks.

**Comment by NathanHawks** [comment]
Nobody has committed a single line of code in over a year and a half :(

**Comment by wadbr** [comment]
Yeah this is probably dead by now right? I mean the chrome extension still works really well (basically only missing v.reddit support)  but the rewrite isn't going anywhere I'm guessing

**Comment by NathanHawks** [comment]
Hopefully they're staging somewhere private and actually hard at work. They may just not want to push something unfinished.

**Comment by aproposnix** [comment]
Well, I know they are still managing the web version (reddit6.com) because I occasionally have to request they fix access to it (esp., things like expired SSL's). 

I wish someone would fork the project and start hacking. I can't code or I would.

**Comment by PCITechie** [comment]
I would fork and continue it, but I don't do Javascript, CSS, or HTML...

**Comment by snwfog** [comment]
I decided to build an alternative to Reditr since the development of version 2 seems to have staled. 
Feel free to check it out the early beta at http://rdddeck.com.
